---
# tasks file for epel
- name: install epel-release
  package:
    name: "{{ epel_url }}"
    state: present
  notify:
    - yum update cache
  when:
    - ansible_distribution in [ "CentOS", "RedHat", "Amazon" ]
  register: epel_install_epel_release
  until: epel_install_epel_release is succeeded
  retries: 3
