---
- name: Adding IP addresses of Servers
  hosts: localhost
  gather_facts: False
  vars_prompt:
    - name: storage_server
      prompt: "Enter IP address of Storage Server"
      private: no

    - name: web_server
      prompt: "Enter IP address of Web Server"
      private: no

    - name: database_server
      prompt: "Enter IP address of Database Server"
      private: no

  pre_tasks:
    - name: Make variable persistant
      set_fact:
        storage_server: "{{ storage_server }}"
        web_server: "{{ web_server }}"
        database_server: "{{ database_server }}"

  roles:
    - name: add-servers

- name: Configuring Storage Server
  hosts: storage 
  gather_facts: False
  vars_files:
    - vars/variables.yml
  pre_tasks:
    - block:    
        - name: "Check if two logical volume {{ webapp_storage }} and {{ database_storage }} are present on storage server or not"
          shell: "lvs {{ webapp_storage }} && lvs {{ database_storage }}"
          changed_when: False
        - debug:
            msg: "Storage Server satisfied all requirements." 
      rescue:
        - debug:
            msg: "LVM's are not configured properly."
  roles:
    - name: configure-nfs-share
    - name: configure-iscsi-target

- name: Configure Database Server
  hosts: database
  gather_facts: False
  vars_files:
    - vars/variables.yml
  roles:
    - name: configure-database-server

- name: Configure web server 
  hosts: webserver
  gather_facts: False
  vars_files:
    - vars/variables.yml
  roles:
    - name: configure-web-server

- name: VtigerCRM Pre-requisites changes for database server
  hosts: database
  gather_facts: False
  roles:
    - name: vtigercrm-mysql-requirements

- name: VtigerCRM Pre-requisites changes for web server
  hosts: webserver
  roles:
    - name: add-epel
    - name: vtigercrm-php-requirements
