---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux" tag="1"
    - image="amazonlinux" tag="latest"
    - image="centos" tag="7"
    - image="centos" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "UCtHXxGlko9yhbPzIlhDNINhnYk1bUCkTyQzHNN/toT37uzzTQGsQksb8AOxS5C3LhkgTcMucM68rlM4yaaDize92ppWOfpePnqasRSLRPnI9HpHF5toJbnEZUA/1L2SBn1oHzrFBpoFiizTSt35yuo2uYIc8SSYphksiywtyW47+SErzZB0A+UvQvHSOj1LRqh5KYe1vcR028V8MabwIV0Pt4IccvPBrKbWjZZgyoYJbwhj+H7dXZ3u5Y7dmoLfcpJFPv44iz4o4zg2NRx7yYuVRyhaNOeikScKyjFXL4t+3RyqEfuWHTg5ffwvxIY2gG7fotj5aplxMlc04FASHLYlQwDKRRXb7pkb0fiK6h9CiB2V8iIXUYhj15lDitTJe1MZu2WUTxA/hGK81aI6IwRCPF1nAphS0UcVfi+EyNIO463aW9vW6t53FIdQ5O4MQuH/YkSmP2y/YX3qoAB9mlcglYOWWgoEFvDpJezRouzOA0wGBhKFRtMg8NZnsTU8CMPsjsRRNDb4Y2mcymkzpKT7ljmKyav+EK9Ko9Mizh5CCIMClsxZ4Hg/1bWn+R4y7T7qlzboGonZ2USw6s/sa/bQ69eAw4JC2IIL7EqadBwTeALUBWd1tY0gvuFPLJIG+LX+XRvne85nYC1m7ioUeGsFrjDrodNuMeyxwiEjfYo="
  email: false
